- more vim setting removed (don't convert tabs to spaces) - white space cleanup - convert spaces to tabs - unify formatting for all scripts
git-svn-id: http://svn.pld-linux.org/svn/rc-scripts/trunk@6491 11da6c6d-24c7-0310-97e0-b6d17e038e62

diff --git a/sysconfig/network-scripts/ifdown b/sysconfig/network-scripts/ifdown
--- a/sysconfig/network-scripts/ifdown
+++ b/sysconfig/network-scripts/ifdown
@@ -10,33 +10,33 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
 # Will be removed in the future
 if is_yes "$NETWORKING" ; then
-    if [ -z "$IPV4_NETWORKING" ] ; then
-	echo "NETWORKING is set to YES, but IPV4_NETWORKING is empty!"
-	echo "Please upgrade your config"
-	echo "Assuming you want IPv4 networking"
-	IPV4_NETWORKING=yes
-    fi
+	if [ -z "$IPV4_NETWORKING" ] ; then
+		echo "NETWORKING is set to YES, but IPV4_NETWORKING is empty!"
+		echo "Please upgrade your config"
+		echo "Assuming you want IPv4 networking"
+		IPV4_NETWORKING=yes
+	fi
 fi
 
 DEV=$1
 
 [ -z "$DEV" ] && {
-    nls "Usage: %s <device name>" "ifdown" >&2
-    exit 1
+	nls "Usage: %s <device name>" "ifdown" >&2
+	exit 1
 }
 
 if [ -f "/etc/sysconfig/interfaces/ifcfg-$DEV" ] ; then
-    CONFIG="/etc/sysconfig/interfaces/ifcfg-$DEV"
+	CONFIG="/etc/sysconfig/interfaces/ifcfg-$DEV"
 else
-    CONFIG="$DEV"
+	CONFIG="$DEV"
 fi
 
 if [ "$(id -u)" != "0" ]; then
-    if [ -x /sbin/usernetctl ]; then
-        exec /sbin/usernetctl $CONFIG down
-    fi
-    echo "Users cannot control this device." >&2
-    exit 1
+	if [ -x /sbin/usernetctl ]; then
+		exec /sbin/usernetctl $CONFIG down
+	fi
+	echo "Users cannot control this device." >&2
+	exit 1
 fi
 
 source_config
@@ -48,15 +48,15 @@ OTHERSCRIPT="/etc/sysconfig/network-scripts/ifdown-${DEVICETYPE}"
 
 # shutdown tleds software
 if [ "$TLEDS_DEV" = "$DEVICE" -a -x /usr/bin/tleds ]; then
-    /usr/bin/tleds -qk "$DEVICE"
+	/usr/bin/tleds -qk "$DEVICE"
 fi
 
 if [ -x $OTHERSCRIPT ]; then
-    if [ "$HANDLING" = "0" ]; then
-    	exec $OTHERSCRIPT $CONFIG $2
-    elif [ "$HANDLING" = "1" ]; then
-    	$OTHERSCRIPT $CONFIG $2
-    fi
+	if [ "$HANDLING" = "0" ]; then
+		exec $OTHERSCRIPT $CONFIG $2
+	elif [ "$HANDLING" = "1" ]; then
+		$OTHERSCRIPT $CONFIG $2
+	fi
 fi
 
 # Check to make sure the device is actually up
@@ -68,69 +68,69 @@ if [ "$BOOTPROTO" = "bootp" -o "$BOOTPROTO" = "pump" ]; then
 fi
 
 if [ "$BOOTPROTO" = "dhcp" ]; then
-    if [ -x /sbin/dhcpcd ];then
-        /sbin/dhcpcd -k ${DEVICE}
-	RESULT=$?
-    elif [ -x /sbin/dhclient ];then
-        if [ -f /var/run/dhclient.pid ];then
-            PID=$(cat /var/run/dhclient.pid)
-            if ps ax --no-header|grep -q $PID;then
-                kill $PID
+	if [ -x /sbin/dhcpcd ];then
+		/sbin/dhcpcd -k ${DEVICE}
 		RESULT=$?
-            fi
-        fi
-    elif [ -x /sbin/dhcpxd ];then
-        /sbin/dhcpxd -k ${DEVICE}
-	RESULT=$?
-    elif [ -x /sbin/pump ];then
-        pump -r -i ${DEVICE}
-	RESULT=$?
-    fi
-    sleep 1
+	elif [ -x /sbin/dhclient ];then
+		if [ -f /var/run/dhclient.pid ];then
+			PID=$(cat /var/run/dhclient.pid)
+			if ps ax --no-header|grep -q $PID;then
+				kill $PID
+				RESULT=$?
+			fi
+		fi
+	elif [ -x /sbin/dhcpxd ];then
+		/sbin/dhcpxd -k ${DEVICE}
+		RESULT=$?
+	elif [ -x /sbin/pump ];then
+		pump -r -i ${DEVICE}
+		RESULT=$?
+	fi
+	sleep 1
 fi
 
 if is_wireless_device "${DEVICE}"; then
-    if is_yes "${WLAN_WPA}"; then
-	killproc --pidfile "wpa_supplicant-${DEVICE}.pid" wpa_supplicant > /dev/null 2>&1
-	rm -f "/var/run/wpa_supplicant-${DEVICE}.pid"
-    fi
+	if is_yes "${WLAN_WPA}"; then
+		killproc --pidfile "wpa_supplicant-${DEVICE}.pid" wpa_supplicant > /dev/null 2>&1
+		rm -f "/var/run/wpa_supplicant-${DEVICE}.pid"
+	fi
 fi
-    
+
 vlan_setup
 if is_yes $ETH_VLANS && `echo $DEVICE | grep -q ^eth` ; then
-    if echo "${DEVICE}" | grep -q '\.' ; then
-	# vlan down
-	ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
-	ip link set ${DEVICE} down
-	/sbin/vconfig rem ${DEVICE} 2>&1 > /dev/null
-    else
-	# downujemy interfejs nadrzedny do vlanow
-	for VLANDEVICE in `ls /proc/net/vlan 2> /dev/null | grep ^${DEVICE}` ; do
-	    # najpierw wszystkie vlany po kolei
-	    ip addr flush dev ${VLANDEVICE} 2>&1 | grep -v "Nothing to flush"
-	    ip link set ${VLANDEVICE} down
-	    /sbin/vconfig rem ${VLANDEVICE} 2>&1 > /dev/null
-	done 
-	# a potem dopiero interfejs nadrzedny
-	ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
-	ip link set ${DEVICE} down
-    fi
+	if echo "${DEVICE}" | grep -q '\.' ; then
+		# vlan down
+		ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
+		ip link set ${DEVICE} down
+		/sbin/vconfig rem ${DEVICE} 2>&1 > /dev/null
+	else
+		# downujemy interfejs nadrzedny do vlanow
+		for VLANDEVICE in `ls /proc/net/vlan 2> /dev/null | grep ^${DEVICE}` ; do
+			# najpierw wszystkie vlany po kolei
+			ip addr flush dev ${VLANDEVICE} 2>&1 | grep -v "Nothing to flush"
+			ip link set ${VLANDEVICE} down
+			/sbin/vconfig rem ${VLANDEVICE} 2>&1 > /dev/null
+		done
+		# a potem dopiero interfejs nadrzedny
+		ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
+		ip link set ${DEVICE} down
+	fi
 else
-    ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
-    ip link set ${DEVICE} down
-fi    
+	ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
+	ip link set ${DEVICE} down
+fi
 
 if [ "$HANDLING" = "4" ]; then
-    exit 0
+	exit 0
 fi
 
 if [ -n "$RESULT" ] ; then
-    if [ "$RESULT" -ne "0" ]; then
-	return $RESULT
-    fi
+	if [ "$RESULT" -ne "0" ]; then
+		return $RESULT
+	fi
 fi
 
 exec /etc/sysconfig/network-scripts/ifdown-post $CONFIG
 
 # This must be last line !
-# vi:syntax=sh:ts=8:sw=4
+# vi:syntax=sh
diff --git a/sysconfig/network-scripts/ifdown-irda b/sysconfig/network-scripts/ifdown-irda
--- a/sysconfig/network-scripts/ifdown-irda
+++ b/sysconfig/network-scripts/ifdown-irda
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 #    ifdown-irda - IrDA configuration script
-#    Copyright (C) 2001  Arkadiusz Mi¶kiewicz <misiek@pld-linux.org>
+#    Copyright (C) 2001 Arkadiusz Mi¶kiewicz <misiek@pld-linux.org>
 #
 #    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -30,7 +30,7 @@ CONFIG=$1
 source_config
 
 if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
-    exit
+	exit
 fi
 
 . /etc/sysconfig/network
@@ -43,36 +43,36 @@ ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"
 
 PID=$(pidof irattach)
 for x in $PID; do
-    if grep -q "$MODEMPORT" /proc/$x/cmdline; then
-	logger -p daemon.info -t ifdown-sl "signal TERM send to \"$(ps -o cmd=$x)\" - this should be irattach"
-	kill -TERM $x
-	PID=$x
-    fi
+	if grep -q "$MODEMPORT" /proc/$x/cmdline; then
+		logger -p daemon.info -t ifdown-sl "signal TERM send to \"$(ps -o cmd=$x)\" - this should be irattach"
+		kill -TERM $x
+		PID=$x
+	fi
 done
-					    
+
 if [ -z "$PID" ]; then
-      exit 1
+	exit 1
 fi
 
 kill $PID > /dev/null 2>&1
 if [ ! -d /proc/$PID ]; then
-    /etc/sysconfig/network-scripts/ifdown-post $1
-    exit 0
+	/etc/sysconfig/network-scripts/ifdown-post $1
+	exit 0
 fi
 sleep 2
 if [ ! -d /proc/$PID ]; then
-    /etc/sysconfig/network-scripts/ifdown-post $1
-    exit 0
+	/etc/sysconfig/network-scripts/ifdown-post $1
+	exit 0
 fi
 
 kill -KILL $PID > /dev/null 2>&1
 if [ -d /proc/$PID ]; then
-    logger -p daemon.info -t ifdown-irda "$(nls 'ifdown-%s unable to kill %s for %s' "irda" "irattach" "$DEVICE")" &
+	logger -p daemon.info -t ifdown-irda "$(nls 'ifdown-%s unable to kill %s for %s' "irda" "irattach" "$DEVICE")" &
 else
-    /etc/sysconfig/network-scripts/ifdown-post $1
+	/etc/sysconfig/network-scripts/ifdown-post $1
 fi
 
 exit 1
-	    
+
 # This must be last line !
-# vi:syntax=sh:ts=8:sw=4
+# vi:syntax=sh
diff --git a/sysconfig/network-scripts/ifdown-sl b/sysconfig/network-scripts/ifdown-sl
--- a/sysconfig/network-scripts/ifdown-sl
+++ b/sysconfig/network-scripts/ifdown-sl
@@ -19,17 +19,17 @@ rm -f /var/run/sl-$DEVICE.dev
 
 # we can use dip or direct slip connection via slattach
 if is_no "$DIRECT_CONNECT"; then
-    PID=$(pidof dip-$DEVICE)
+	PID=$(pidof dip-$DEVICE)
 else
-    PID=$(pidof slattach)
-    for x in $PID; do
-	if grep -q "$MODEMPORT" /proc/$x/cmdline; then
-	    logger -p daemon.info -t ifdown-sl \
-		"signal TERM send to \"$(ps -o cmd= $x)\" - this should be slattach"
-	    kill -TERM $x
-	    PID=$x
-	fi
-    done
+	PID=$(pidof slattach)
+	for x in $PID; do
+		if grep -q "$MODEMPORT" /proc/$x/cmdline; then
+			logger -p daemon.info -t ifdown-sl \
+				"signal TERM send to \"$(ps -o cmd= $x)\" - this should be slattach"
+			kill -TERM $x
+			PID=$x
+		fi
+	done
 fi
 #
 # The proctitle for connected dip daemons is actually "-dip (ipaddr)"
@@ -37,32 +37,31 @@ fi
 # Grab the PID of connected dial-out daemon.
 #
 if [ -z "$PID" ]; then
-    PID=$(pidof -- -dip\ \($IPADDR\))
+	PID=$(pidof -- -dip\ \($IPADDR\))
 fi
 if [ -z "$PID" ]; then
-    exit 1
+	exit 1
 fi
 
 kill $PID > /dev/null 2>&1
 if [ ! -d /proc/$PID ]; then
-    /etc/sysconfig/network-scripts/ifdown-post $1
-    exit 0
+	/etc/sysconfig/network-scripts/ifdown-post $1
+	exit 0
 fi
 sleep 2
 if [ ! -d /proc/$PID ]; then
-    /etc/sysconfig/network-scripts/ifdown-post $1
-    exit 0
+	/etc/sysconfig/network-scripts/ifdown-post $1
+	exit 0
 fi
 
 kill -KILL $PID > /dev/null 2>&1
 if [ -d /proc/$PID ]; then
-    logger -p daemon.info -t ifdown-sl "ifdown-sl unable to kill sl-$DEVICE" &
+	logger -p daemon.info -t ifdown-sl "ifdown-sl unable to kill sl-$DEVICE" &
 else
-    /etc/sysconfig/network-scripts/ifdown-post $1
+	/etc/sysconfig/network-scripts/ifdown-post $1
 fi
 
 exit 1
 
-
 # This must be last line !
-# vi:syntax=sh:ts=8:sw=4
+# vi:syntax=sh
