- more TOTALNEW merge (ppp, irda, other vlan, wireless). ALPHA
git-svn-id: http://svn.pld-linux.org/svn/rc-scripts/trunk@1032 11da6c6d-24c7-0310-97e0-b6d17e038e62

diff --git a/sysconfig/network-scripts/ifdown-ppp b/sysconfig/network-scripts/ifdown-ppp
--- a/sysconfig/network-scripts/ifdown-ppp
+++ b/sysconfig/network-scripts/ifdown-ppp
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#	$Id: ifdown-ppp,v 1.11 2002/05/11 09:50:53 misiek Exp $
+#	$Id: ifdown-ppp,v 1.12 2002/07/13 16:25:07 misiek Exp $
 #
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
@@ -18,40 +18,37 @@ fi
 
 # set all major variables
 setup_ip_param
-
 get_ppp_device_and_pid
 
 if [ -z "$PID" ]; then
-  exit 1
+    exit 1
 fi
 
 rm -f /var/run/ppp-$DEVICE.pid
 
-# pppd might have chat as a child; remember chat's pid to kill after pppd.
-# (After, not before, so that pppd doesn't just restart it).
+[ ! -d /proc/${PID} ] && exit 0
 
-CHATPID=$(ps axl | awk '$4 ~ /^'"$PID"'$/ {print $3}' 2>/dev/null)
+kill -TERM ${PID} > /dev/null 2>&1
 
-kill $PID > /dev/null 2>&1
-[ -n "$CHATPID" ] && kill $CHATPID > /dev/null 2>&1
-if [ ! -d /proc/$PID ]; then
-  /etc/sysconfig/network-scripts/ifdown-post $1
-  exit 0
-fi
 sleep 2
-if [ ! -d /proc/$PID ]; then
-  /etc/sysconfig/network-scripts/ifdown-post $1
-  exit 0
+if [ ! -d /proc/${PID} ]; then
+    /etc/sysconfig/network-scripts/ifdown-post $1
+    exit 0
 fi
 
-kill -KILL $PID > /dev/null 2>&1
-if [ -d /proc/$PID ]; then
-  logger -p daemon.info -t ifdown-ppp "ifdown-ppp unable to kill pppd-$DEVICE" &
-else
-  /etc/sysconfig/network-scripts/ifdown-post $1
+sleep 2
+[ -d /proc/${PID} ] && sleep 5
+
+if [ ! -d /proc/${PID} ]; then
+    /etc/sysconfig/network-scripts/ifdown-post $1
+    exit 0
 fi
+
+kill -KILL ${PID} > /dev/null 2>&1
+logger -p daemon.info -t ifdown-ppp "ifdown-ppp unable to nicely kill pppd-$DEVICE" &
 
 exit 1
 
 # This must be last line !
 # vi:syntax=sh:tw=78:ts=8:sw=4
+
