- try last resort in setting MODEMPORT - compatibility change.
git-svn-id: http://svn.pld-linux.org/svn/rc-scripts/trunk@9801 11da6c6d-24c7-0310-97e0-b6d17e038e62

diff --git a/sysconfig/network-scripts/ifup-ppp b/sysconfig/network-scripts/ifup-ppp
--- a/sysconfig/network-scripts/ifup-ppp
+++ b/sysconfig/network-scripts/ifup-ppp
@@ -138,8 +138,13 @@ else
 fi
 
 if [ -z "$MODEMPORT" ]; then
-	echo >&2 "Missing modemport!"
-	exit 1
+	# Last try:
+	if [ "${PPPOA_VPI}" -a "${PPPOA_VCI}" ]; then
+		MODEMPORT=${PPPOA_VPI}.${PPPOA_VCI}
+	else
+		echo >&2 "Missing modemport!"
+		exit 1
+	fi
 fi
 
 if [ -z "$HOLDOFF" ]; then
