- fail on required MODEMPORT (or set it to /dev/modem?)
git-svn-id: http://svn.pld-linux.org/svn/rc-scripts/trunk@9279 11da6c6d-24c7-0310-97e0-b6d17e038e62

diff --git a/sysconfig/network-scripts/ifup-ppp b/sysconfig/network-scripts/ifup-ppp
--- a/sysconfig/network-scripts/ifup-ppp
+++ b/sysconfig/network-scripts/ifup-ppp
@@ -131,6 +131,11 @@ else
 	fi
 fi
 
+if [ -z "$MODEMPORT" ]; then
+	echo >&2 "Missing modemport!"
+	exit 1
+fi
+
 if [ -z "$HOLDOFF" ]; then
 	HOLDOFF=30
 fi
