Synced with rc-scripts-0.0.1 from old repo.
git-svn-id: http://svn.pld-linux.org/svn/rc-scripts/trunk@362 11da6c6d-24c7-0310-97e0-b6d17e038e62

diff --git a/rc.d/init.d/functions-ip6 b/rc.d/init.d/functions-ip6
--- a/rc.d/init.d/functions-ip6
+++ b/rc.d/init.d/functions-ip6
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 #!F:functions-ip6
 #
@@ -11,28 +11,48 @@
 # 	tunnels-up-ip6, tunnels-down-ip6
 #
 #!C:Copyright 1997-1998 Peter Bieringer <pb@bieringer.de>
+#!C:some code by Gregorz Stanislawski <stangrze@open.net.pl>
 #
-#!V:Version: 2.39 01.05.1998
+#!V:Version: 2.41a 10.11.1998
 #
-# Changes from:
-# 2.32: exchange 'exit' with 'return' (bad mistake...)
-# 2.33: new debug level (bit 2) 
-# 2.34: minor improvements 
-# 2.35: info  
-# 2.36: add IP6FORWARDING switch (to differ between a host and a router)
-# 2.37: add forwarding switch for kernel versions >= 2.1.90 (idea by Dan Anderson anderson@computer.org)
-# 2.38: make IP6FORWARDING independed from IP6GATEWAYCONFIG
-
+# Changes to:
+#  2.34: new debug level (bit 2) 
+#  2.35: minor improvements 
+#  2.36: info  
+#  2.37: add IP6FORWARDING switch (to differ between a host and a router)
+#  2.38: add forwarding switch for kernel versions >= 2.1.90
+#        (idea by Dan Anderson anderson@computer.org)
+#  2.39: make IP6FORWARDING independed from IP6GATEWAYCONFIG
+#  2.40: NBMA tunnel setup support, see 'network-ip6.conf v2.11+' for details
+#  2.41: Error sign to get a right exit value of each function (only 0 = ok)
+#  2.41a: 
+#    - Scripts now make use of iproute2 package by Alexey Kuznietsov.
+#    - Config file splited to 2 files: network-ip6.conf & tunnels-ip6.conf.
+#    - Changes to file layout. for better incorporation into PLD or Redhat systems. 
+#    - Removed support for radvd (Most of people use mrtd anyway)
+#    - Removed support fod nbma tunnel conf.
+ 
 IP6NETWORKFILE=/etc/sysconfig/network-ip6
 
 # debug level & 2 prevents from executing any network configuration
 # debug level & 4 shows messages in the test section
+
+# Return values
+#  0 = ok
+#  1 = error occurs
+#  2 = not enabled, i.e. no IPv6 kernel support or switched off by configuration
+
+# File as error sign
+EXITFAIL=/tmp/functions-ip6.error
 
 
 ##### Test for IPv6
 
 function test-ip6()
 {
+    # Remove error sign file
+    rm -f $EXITFAIL
+    
     if [ "$IP6DEBUG" = "" ] ; then IP6DEBUG=0; fi
 
     if ! [ $[ $IP6DEBUG & 4 ] = 0 ] ; then
@@ -45,12 +65,7 @@ function test-ip6()
     fi
 
     if ! [ -f /proc/net/if_inet6 ]; then
-        if ! [ $[ $IP6DEBUG & 4 ] = 0 ] ; then
-            echo -e "\a Not compiled for IPv6 - stop!"
-        else
-            echo -e "\a Kernel not compiled for IPv6 - stop!"
-        fi
-        return 1
+        return 2
     else
         if ! [ $[ $IP6DEBUG & 4 ] = 0 ] ; then
             echo " Ok!"
@@ -91,8 +106,10 @@ function test-ip6()
     if ! [ "$IP6NETWORKING" = "yes" ] ; then
         if ! [ $[ $IP6DEBUG & 4 ] = 0 ] ; then
 	    echo -e "\a No - stop!"
+	else
+	    echo -e "\a IPv6 configuration isn't enabled - stop!"
 	fi
-        return 3
+        return 2
     else
         if ! [ $[ $IP6DEBUG & 4 ] = 0 ] ; then
             echo " Yes!"
@@ -124,14 +141,25 @@ function return-ip6()
 function ifup-routes-ip6()
 {
     # Run IPv6 test
-    test-ip6 || return 1    
+    test-ip6 || return    
 
     # Allow forwarding option, host is a router?
     if [ "$IP6FORWARDING" = "yes" ]; then
         # Switch on IPv6 forwarding in the kernel if off
 	
+	# Which mechanism? kernel >= 2.1.90 uses forwarding switch by device
+        if [ -f /proc/sys/net/ipv6/forwarding ]; then
+	    # for kernel < 2.1.90
+            if ! [ "`cat /proc/sys/net/ipv6/forwarding`" = "1" ]; then
+                echo "  Switch on IPv6 forwarding in the kernel"
+                if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
+    	    	    echo "1" > /proc/sys/net/ipv6/forwarding
+        	fi
+            fi
+	fi
+	
 	if [ -f /proc/sys/net/ipv6/conf/all/forwarding ]; then
-
+	    # for kernel >= 2.1.90
 	    for i in /proc/sys/net/ipv6/conf/*/forwarding; do
                 if ! [ "`cat $i`" = "1" ]; then
 		    device=`echo $i | cut -d / -f 7` 
@@ -155,6 +183,7 @@ function ifup-routes-ip6()
 
     # Device "lo" need no IPv6 configuration
     if [ "$1" = "lo" ]; then
+        echo "  Device lo needs no IPv6 routing configuration"
         return 1;
     fi
 
@@ -177,32 +206,41 @@ function ifup-routes-ip6()
 
     grep "^$1" $IP6ROUTEFILE | while read device key gateway route; do
 	if [ "$key" = "route" ]; then
-            echo "  Add IPv6 route $route gw $gateway dev $device"
+            echo "  Add IPv6 route $route via $gateway dev $device"
             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-                 route -A inet6 add $route gw $gateway dev $device
+                route -A inet6 add $route gw $gateway metric 1 dev $device || touch $EXITFAIL
 	    fi
         fi
     done
 
     return-ip6
+    
+    if [ -f $EXITFAIL ]; then
+	return 1
+	rm -f $EXITFAIL
+    else
+	return 0
+    fi
 }
 
 
 function ifdown-routes-ip6()
 {
     # Run IPv6 test
-    test-ip6 || return 1    
+    test-ip6 || return
 
     if ! [ "$IP6GATEWAYCONFIG" = "yes" ]; then return 1; fi
 
     echo " Clear IPv6 routes"
 
     if [ "$1" = "" ]; then
+	echo -e "\a  Usage: $0 <net-device>"
 	return 1
     fi
     
     # Device "lo" need no IPv6 configuration
     if [ "$1" = "lo" ]; then
+        echo "  Device lo needs no IPv6 routing configuration"
         return 1;
     fi
 
@@ -225,14 +263,21 @@ function ifdown-routes-ip6()
     
     grep "^$1" $IP6ROUTEFILE | while read device key gateway route; do
 	if [ "$key" = "route" ]; then
-            echo "  Del IPv6 route $route gw $gateway dev $device"
+            echo "  Del IPv6 route $route via $gateway dev $device"
             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-                route -A inet6 del $route gw $gateway dev $device
+                route -A inet6 del $route gw $gateway dev $device || touch $EXITFAIL
  	    fi
         fi
     done
 
     return-ip6
+    
+    if [ -f $EXITFAIL ]; then
+	return 1
+	rm -f $EXITFAIL
+    else
+	return 0
+    fi
 }
 
 
@@ -241,8 +286,9 @@ function ifdown-routes-ip6()
 ## Configure tunnels up
 function tunnels-up-ip6()
 {
+echo "test"
     # Run IPv6 test
-    test-ip6 || return 1    
+    test-ip6 || return    
 
     if ! [ "$IP6TUNNELCONFIG" = "yes" ]; then return 1; fi
 
@@ -268,55 +314,53 @@ function tunnels-up-ip6()
         # get IPv6-over-IPv4 tunnels up (enables automatic to 0::0/96)
         echo "  Get IPv6-over-IPv4 tunnels up (enables automatic to 0::0/96)"
         if [ $[ $IP6DEBUG & 2 ] = 0 ] ; then
-            ifconfig sit0 up
+            ifconfig sit0 up || touch $EXITFAIL
         fi
 
         # Take configured tunnels from $IP6TUNNELFILE
-        TUNNELDEV=1
 
-	grep "^sit" $IP6TUNNELFILE | while read device key ip4gateway;  do  
-
-            if [ "$device" = "sit$TUNNELDEV" ]; then
-
+	grep -v "^#" $IP6TUNNELFILE | while read device key local remote ttl realdev;  do  
 	        if [ "$key" = "tunnel" ]; then
-                    echo "  Add tunnel sit$TUNNELDEV to $ip4gateway"
+                    echo "  Add tunnel $device to $remote"
 	    
 	            # Set up a tunnel
-                    if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-	                ifconfig sit0 tunnel ::$ip4gateway
-                    fi
+#                    if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
+#	                ifconfig sit0 tunnel ::$remote || touch $EXITFAIL
+#                    fi
             
 	            # Start tunnel device sit?
                     if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-	                ifconfig sit$TUNNELDEV up
+	                iptunnel add $device mode sit remote $remote local $local ttl $ttl dev $realdev
+echo "Tunnel $device added"
+			ifconfig $device up arp multicast
+echo "Tunnel $device is configured and up"
+ 			route -A inet6 add fe80::$remote dev $device
+echo "Routing to $remote via $device added"
                     fi
                 
-                    grep "^sit$TUNNELDEV" $IP6TUNNELFILE | while { read device key network; } do
+                    grep "^$device" $IP6TUNNELFILE | while { read device key network; } do
                     
 	                if [ "$key" = "route" ]; then
-                            echo "   Add route to tunnel sit$TUNNELDEV for network $network"
+                            echo "   Add route to tunnel $device for network $network"
 	    
 	                    # Set route to tunnel
                             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-	                        route -A inet6 add $network gw fe80::$ip4gateway dev sit$TUNNELDEV
+                            route -A inet6 add $network gw fe80::$remote dev $device || touch $EXITFAIL
                             fi
     		        fi
                     done
 
-                    # Increment for next tunnel
-                    TUNNELDEV=$[ $TUNNELDEV + 1 ]
                 fi
-            fi 
 	done 
-        
-
-#won't work, problem with local scope in while...
-#        if [ $[ $TUNNELDEV < 2 ] = 1 ]; then
-#           echo -e "\a  No tunnels configured!"
-#            echo "  $IP6TUNNELFILE: possible error in your tunnel setup!"
-#        fi
 
     return-ip6
+    
+    if [ -f $EXITFAIL ]; then
+	return 1
+	rm -f $EXITFAIL
+    else
+	return 0
+    fi
 }	
 
 
@@ -325,7 +369,7 @@ function tunnels-up-ip6()
 function tunnels-down-ip6()
 {
     # Run IPv6 test
-    test-ip6 || return 1    
+    test-ip6 || return
 
     if ! [ "$IP6TUNNELCONFIG" = "yes" ]; then return 1; fi
 
@@ -352,46 +396,47 @@ function tunnels-down-ip6()
 
         # Take configured tunnels from $IP6TUNNELFILE
 
-	grep "^sit" $IP6TUNNELFILE | while read device key ip4gateway; do
-
-            if [ "$device" = "sit$TUNNELDEV" ]; then
+	grep -v "^#" $IP6TUNNELFILE | while read device key local remote ttl realdev;  do  
 
 	        if [ "$key" = "tunnel" ]; then
-                
-                    grep "^sit$TUNNELDEV" $IP6TUNNELFILE | while read device key network; do
+                    grep "^$device" $IP6TUNNELFILE | while read device key host; do
                     
 	                if [ "$key" = "route" ]; then
-                            echo "   Del route to tunnel sit$TUNNELDEV for network $network"
+                            echo "   Del route to tunnel $device for host $host"
 	    
 	                    # Set route to tunnel
                             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-	                        route -A inet6 del $network gw fe80::$ip4gateway dev sit$TUNNELDEV
+	                        route -A inet6 del $network gw fe80::$remote dev $device || touch $EXITFAIL
                             fi
     		        fi
                     done
 
-                    echo "  Delete tunnel sit$TUNNELDEV"
+                    echo "  Delete tunnel $device"
 	    
 	            # Stop tunnel device sit?
                     if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-	                ifconfig sit$TUNNELDEV down
+	                ifconfig $device down  
+			iptunnel del $device || touch $EXITFAIL
                     fi
 
-                    # Increment for next tunnel
-                    TUNNELDEV=$[ $TUNNELDEV + 1 ]
-                    
                 fi
-            fi
 	done
 
         # Stop IPv6-over-IPv4 tunnels
         echo "  Stop IPv6-over-IPv4 tunnels"
         if [ $[ $IP6DEBUG & 2 ] = 0 ] ; then 
 	    echo "  Delete basic tunnel device sit0"
-            ifconfig sit0 down
+            ifconfig sit0 down || touch $EXITFAIL
         fi
 
     return-ip6
+    
+    if [ -f $EXITFAIL ]; then
+	return 1
+	rm -f $EXITFAIL
+    else
+	return 0
+    fi
 }
 
 	
@@ -402,16 +447,18 @@ function tunnels-down-ip6()
 function ifup-ip6()
 {
     if [ "$1" = "" ]; then
+	echo -e "\a  Usage: $0 <net-device>"
 	return 1
     fi
 
     # Device "lo" need no IPv6 configuration
     if [ "$1" = "lo" ]; then
+        echo "  Device lo needs no IPv6 configuration"
         return 1;
     fi
 
     # Run IPv6 test
-    test-ip6 || return 1    
+    test-ip6 || return    
 
     echo " Brings interface $1 up for IPv6"
 
@@ -424,17 +471,24 @@ function ifup-ip6()
 	if [ "$key" = "iface" ]; then
             echo "  Add for dev $device IPv6 address $prefix:$suffix/$length"
             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-                ifconfig $device add $prefix:$suffix/$length
+                ifconfig $device add $prefix:$suffix/$length || touch $EXITFAIL
 	    fi
     
             echo "  Add IPv6 route $prefix::0/$length through dev $device"
             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-                route -A inet6 add $prefix::0/$length dev $device
+                route -A inet6 add $prefix::0/$length dev $device || touch $EXITFAIL
 	    fi
         fi
     done
 
     return-ip6
+
+    if [ -f $EXITFAIL ]; then
+	return 1
+	rm -f $EXITFAIL
+    else
+	return 0
+    fi
 }
 
 
@@ -443,6 +497,7 @@ function ifup-ip6()
 function ifdown-ip6()
 {
     if [ "$1" = "" ]; then
+	echo -e "\a  Usage: $0 <net-device>"
 	return 1
     fi
 
@@ -450,7 +505,7 @@ function ifdown-ip6()
     if [ "$1" = "lo" ]; then return 0; fi
 
     # Run IPv6 test
-    test-ip6 || return 1    
+    test-ip6 || return    
 
     echo " Brings interface $1 down from IPv6"
 
@@ -463,15 +518,22 @@ function ifdown-ip6()
 	if [ "$key" = "iface" ]; then
             echo "  Del IPv6 route $prefix::0/$length through dev $device"
             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-                route -A inet6 del $prefix::0/$length dev $device
+                route -A inet6 del $prefix::0/$length dev $device || touch $EXITFAIL
             fi
 
             echo "  Del for dev $device IPv6 address $prefix:$suffix/$length"
             if [ $[ $IP6DEBUG & 2 ] = 0 ]; then
-                ifconfig $device del $prefix:$suffix/$length
+                ifconfig $device del $prefix:$suffix/$length || touch $EXITFAIL
 	    fi
         fi
     done
 
     return-ip6
+    
+    if [ -f $EXITFAIL ]; then
+	return 1
+	rm -f $EXITFAIL
+    else
+	return 0
+    fi
 }
diff --git a/rc.d/init.d/network b/rc.d/init.d/network
--- a/rc.d/init.d/network
+++ b/rc.d/init.d/network
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/bin/sh
 #
 # network       Bring up/down networking
 #
-# chkconfig: 345 10 97
+# chkconfig: 2345 10 90
 # description: Activates/Deactivates all network interfaces configured to \
 #              start at boot time.
 # probe: true
@@ -21,20 +21,20 @@ if [ -f /etc/sysconfig/pcmcia ]; then
 fi
 
 if [ -f /etc/sysconfig/network-ip6 ]; then
-	. /etc/sysconfig/network-ip6
+       . /etc/sysconfig/network-ip6
 fi
 
+
 # Check that networking is up.
-[ ${NETWORKING} = "no" ] && exit 0
+[ "${NETWORKING}" = "no" ] && exit 0
 
 [ -x /sbin/ifconfig ] || exit 0
 
 # Load IPv6 module
-
-if [ ${IP6NETWORKING} = "yes" ]; then
-	if [ -r /lib/modules/`uname -r`/ipv6/ipv6.o ]; then
-	/sbin/modprobe net-pf-10
-	fi
+if [ "${IP6NETWORKING}" = "yes" ]; then
+       if [ -r /lib/modules/`uname -r`/ipv6/ipv6.o ]; then
+       /sbin/modprobe net-pf-10
+       fi
 fi
 
 # Even if IPX is configured, without the utilities we can't do much
@@ -61,46 +61,85 @@ ipv4_forward_set ()
 	    else
 		if [ "$FORWARD_IPV4" = "no" -o "$FORWARD_IPV4" = "false" ]; then
 		    value=0
-		    message="Disabling IPv4 packet forwarding."
+		    message="Disabling IPv4 packet forwarding: "
 		else
 		    value=1
-		    message="Enabling IPv4 packet forwarding."
+		    message="Enabling IPv4 packet forwarding :"
 		fi
 
 		if [ $value != `cat /proc/sys/net/ipv4/ip_forward` ]; then
 		    show $message
 		    busy
 		    echo "$value" > /proc/sys/net/ipv4/ip_forward
-		    deltext
-		    ok
+		    deltext; ok
 		fi
 	    fi
 	fi
 }
 
-ipv4_spoof_protection ()
-{
-# This is the best method: turn on Source Address Verification and get
-# spoof protection on all current and future interfaces.
-if [ -e /proc/sys/net/ipv4/conf/all/rp_filter ]; then
-  show Setting up IP spoofing protection
-  busy
-  for f in /proc/sys/net/ipv4/conf/*/rp_filter; do
-      echo 1 > $f
-  done
-  deltext
-  ok
-  else
-  deltext
-  fail
-  echo "PROBLEMS SETTING UP IP SPOOFING PROTECTION.  BE WORRIED!"
-fi
+ipv4_spoofing_protection ()
+ {
+        if [ -d /proc/sys/net/ipv4 ]; then
+            # people could have left this out of their kernel, which isn't
+            # exactly an error
+            if [ ! -f /proc/sys/net/ipv4/conf/all/rp_filter ] ; then
+                echo "/proc/sys/net/ipv4/conf/all/rp_filter is missing --" \
+                        "cannot control IP spoofing protection" >&2
+            else
+               if [ "$SPOOFING_IPV4" = "no" -o "$SPOOFING_IPV4" = "false" ]; then
+                    value=0
+                    message="Disabling IPv4 spoofing protection: "
+                else
+                    value=1
+                    message="Enabling IPv4 spoofing protection: "
+                fi
+
+                if [ $value != `cat /proc/sys/net/ipv4/conf/all/rp_filter` ]; then
+                    show $message
+                    busy
+                   for f in /proc/sys/net/ipv4/conf/*/rp_filter; do
+                        echo $value > $f
+                   done
+                    deltext
+                    ok
+                fi
+            fi
+       fi
 }
+
+ipv4_icmp_echo_ignore_broadcasts ()
+{
+        if [ -d /proc/sys/net/ipv4 ]; then
+            # people could have left this out of their kernel, which isn't
+            # exactly an error
+            if [ ! -f /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts ] ; then
+                echo "/proc/sys/net/ipv4/icmp_echo_ignore_broadcasts is missing --" \
+                        "cannot control IP ignoring icmp to broadcasts" >&2
+            else
+                if [ "$IGNORE_ICMP_BCAST_IPV4" = "no" -o "$IGNORE_ICMP_BCAST_IPV4" = "false" ]; then
+                    value=0
+                    message="Disabling IPv4 ign icmp_echo to our bcasts: "
+                else
+                    value=1
+                    message="Enabling IPv4 ign icmp_echo to our bcasts: "
+                fi
+
+                if [ $value != `cat /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts` ]; then
+                    show $message
+                    busy
+                    echo "$value" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
+                    deltext
+                    ok
+                fi
+            fi
+       fi
+ }
 
 # See how we were called.
 case "$1" in
   start)
 	ipv4_forward_set
+	ipv4_icmp_echo_ignore_broadcasts
 
 	./ifup ifcfg-lo
 
@@ -116,11 +155,14 @@ case "$1" in
 		./ifup $i boot
 	done
 
-	ipv4_spoof_protection
+	ipv4_spoofing_protection
 
         touch /var/lock/subsys/network
         ;;
   stop)
+	SPOOFING_IPV4=no
+	ipv4_spoofing_protection
+
 	for i in $interfaces; do
 		./ifdown $i boot
 	done
@@ -130,90 +172,29 @@ case "$1" in
 	    ;;
 	esac
 	./ifdown ifcfg-lo
-	echo "Disabling IPv4 packet forwarding."
+	show "Disabling IPv4 packet forwarding: "
+	busy
 	echo 0 > /proc/sys/net/ipv4/ip_forward
+	deltext; ok
+
+	IGNORE_ICMP_BCAST_IPV4=no
+	ipv4_icmp_echo_ignore_broadcasts
+
         rm -f /var/lock/subsys/network
         ;;
   status)
 	echo "Configured devices:"
 	echo lo $interfaces
 
-	if [ -x /bin/linuxconf ] ; then
-		eval `/bin/linuxconf --hint netdev`
-		echo "Devices that are down:"
-		echo $DEV_UP
-		echo "Devices with modified configuration:"
-		echo $DEV_RECONF
-	else
-		echo "Currently active devices:"
-		echo `/sbin/ifconfig | grep ^[a-z] | awk '{print $1}'`
-	fi
+	echo "Currently active devices:"
+	echo `/sbin/ifconfig | grep ^[a-z] | awk '{print $1}'`
 	;;
   restart)
 	$0 stop
 	$0 start
 	;;
-  reload)
-	if [ -x /bin/linuxconf ] ; then
-		eval `/bin/linuxconf --hint netdev`
-		if [ "$RECONF_IPV4ROUTING" = "yes" ] ; then
-			ipv4_forward_set
-		fi
-		for device in $DEV_UP ; do
-			./ifup $device
-		done
-		for device in $DEV_DOWN ; do
-			./ifdown $device
-		done
-		for device in $DEV_RECONF ; do
-			./ifdown $device
-			./ifup $device
-		done
-		for device in $DEV_RECONF_ALIASES ; do
-			/etc/sysconfig/network-scripts/ifup-aliases $device
-		done
-		for device in $DEV_RECONF_ROUTES ; do
-			/etc/sysconfig/network-scripts/ifup-routes $device
-		done
-		case $IPX in yes|true)
-		  case $IPXINTERNALNET in
-		    reconf)
-			/usr/bin/ipx_internal_net del
-			/usr/bin/ipx_internal_net add $IPXINTERNALNETNUM \
-						      $IPXINTERNALNODENUM
-			;;
-		    add)
-			/usr/bin/ipx_internal_net add $IPXINTERNALNETNUM \
-						      $IPXINTERNALNODENUM
-			;;
-		    del)
-			/usr/bin/ipx_internal_net del
-			;;
-		  esac
-		  ;;
-		esac
-	else
-		$0 restart
-	fi
-	;;
-  probe)
-	if [ -x /bin/linuxconf ] ; then
-		eval `/bin/linuxconf --hint netdev`
-		[ -n "$DEV_UP$DEV_DOWN$DEV_RECONF$DEV_RECONF_ALIASES" -o \
-		  -n "$DEV_RECONF_ROUTES$IPXINTERNALNET" -o \
-		  "$RECONF_IPV4ROUTING" = yes ] && \
-			echo reload
-		exit 0
-	else
-		# if linuxconf isn't around to figure stuff out for us,
-		# we punt.  Probably better than completely reloading
-		# networking if user isn't sure which to do.  If user
-		# is sure, they would run restart or reload, not probe.
-		exit 0
-	fi
-	;;
   *)
-        echo "Usage: network {start|stop|restart|reload|status|probe}"
+        echo "Usage: network {start|stop|restart|status}"
         exit 1
 esac
 
