Avoid heredoc, pdksh makes tmpfile then.
git-svn-id: http://svn.pld-linux.org/svn/rc-scripts/trunk@7878 11da6c6d-24c7-0310-97e0-b6d17e038e62

diff --git a/rc.d/init.d/functions b/rc.d/init.d/functions
--- a/rc.d/init.d/functions
+++ b/rc.d/init.d/functions
@@ -918,14 +918,15 @@ rc_cache_init() {
 	_started=$(progress "WORK")
 	_fail=$(progress "FAIL" "$CFAIL")
 	_died=$(progress "DIED" "$CFAIL")
-	cat <<-EOF 2>/dev/null > "$cachefile"
-	_busy='$_busy';
-	_ok='$_ok';
-	_started='$_started';
-	_fail='$_fail';
-	_died='$_died';
-	_check='$check';
-EOF
+
+	# we don't use heredoc, as ksh attempts to create tempfile then
+	> "$cachefile" || return
+	echo "_busy='$_busy';" >> "$cachefile"
+	echo "_ok='$_ok';" >> "$cachefile"
+	echo "_started='$_started';" >> "$cachefile"
+	echo "_fail='$_fail';" >> "$cachefile"
+	echo "_died='$_died';" >> "$cachefile"
+	echo "_check='$check';" >> "$cachefile"
 }
 
 rc_gettext_init() {
